# Бухгалтерский баланс (форма 0710001) — коды строк для парсинга Excel

# АКТИВ — I. Внеоборотные активы
BS_INTANGIBLE_ASSETS = "1110"
BS_FIXED_ASSETS = "1150"
BS_INVESTMENT_PROPERTY = "1160"
BS_FINANCIAL_INVESTMENTS_NONCURRENT = "1170"
BS_DEFERRED_TAX_ASSETS = "1180"
BS_OTHER_NONCURRENT_ASSETS = "1190"
BS_TOTAL_NONCURRENT_ASSETS = "1100"

# АКТИВ — II. Оборотные активы
BS_INVENTORIES = "1210"
BS_LONG_TERM_ASSETS_FOR_SALE = "1215"
BS_VAT = "1220"
BS_RECEIVABLES = "1230"
BS_FINANCIAL_INVESTMENTS_CURRENT = "1240"
BS_CASH = "1250"
BS_OTHER_CURRENT_ASSETS = "1260"
BS_TOTAL_CURRENT_ASSETS = "1200"
BS_TOTAL_ASSETS = "1600"

# ПАССИВ — III. Капитал
BS_CHARTER_CAPITAL = "1310"
BS_ADDITIONAL_CAPITAL = "1350"
BS_RESERVE_CAPITAL = "1360"
BS_RETAINED_EARNINGS = "1370"
BS_TOTAL_EQUITY = "1300"

# ПАССИВ — IV. Долгосрочные обязательства
BS_BORROWINGS_NONCURRENT = "1410"
BS_DEFERRED_TAX_LIABILITIES = "1420"
BS_ESTIMATED_LIABILITIES_NONCURRENT = "1430"
BS_DEFERRED_INCOME_NONCURRENT = "1440"
BS_OTHER_NONCURRENT_LIABILITIES = "1450"
BS_TOTAL_NONCURRENT_LIABILITIES = "1400"

# ПАССИВ — V. Краткосрочные обязательства
BS_BORROWINGS_CURRENT = "1510"
BS_ACCOUNTS_PAYABLE = "1520"
BS_DEFERRED_INCOME_CURRENT = "1530"
BS_ESTIMATED_LIABILITIES_CURRENT = "1540"
BS_OTHER_CURRENT_LIABILITIES = "1550"
BS_TOTAL_CURRENT_LIABILITIES = "1500"
BS_TOTAL_LIABILITIES = "1700"

accountant_balance_consts = [
    BS_INTANGIBLE_ASSETS,
    BS_FIXED_ASSETS,
    BS_INVESTMENT_PROPERTY,
    BS_FINANCIAL_INVESTMENTS_NONCURRENT,
    BS_DEFERRED_TAX_ASSETS,
    BS_OTHER_NONCURRENT_ASSETS,
    BS_TOTAL_NONCURRENT_ASSETS,
    BS_INVENTORIES,
    BS_LONG_TERM_ASSETS_FOR_SALE,
    BS_VAT,
    BS_RECEIVABLES,
    BS_FINANCIAL_INVESTMENTS_CURRENT,
    BS_CASH,
    BS_OTHER_CURRENT_ASSETS,
    BS_TOTAL_CURRENT_ASSETS,
    BS_TOTAL_ASSETS,
    BS_CHARTER_CAPITAL,
    BS_ADDITIONAL_CAPITAL,
    BS_RESERVE_CAPITAL,
    BS_RETAINED_EARNINGS,
    BS_TOTAL_EQUITY,
    BS_BORROWINGS_NONCURRENT,
    BS_DEFERRED_TAX_LIABILITIES,
    BS_ESTIMATED_LIABILITIES_NONCURRENT,
    BS_DEFERRED_INCOME_NONCURRENT,
    BS_OTHER_NONCURRENT_LIABILITIES,
    BS_TOTAL_NONCURRENT_LIABILITIES,
    BS_BORROWINGS_CURRENT,
    BS_ACCOUNTS_PAYABLE,
    BS_DEFERRED_INCOME_CURRENT,
    BS_ESTIMATED_LIABILITIES_CURRENT,
    BS_OTHER_CURRENT_LIABILITIES,
    BS_TOTAL_CURRENT_LIABILITIES,
    BS_TOTAL_LIABILITIES,
]

# Соответствие кода строки баланса имени поля в AccountantBalanceReport (dict {дата: значение})
CODE_TO_FIELD = {
    BS_INTANGIBLE_ASSETS: "intangible_assets",
    BS_FIXED_ASSETS: "fixed_assets",
    BS_INVESTMENT_PROPERTY: "investment_property",
    BS_FINANCIAL_INVESTMENTS_NONCURRENT: "financial_investments_noncurrent",
    BS_DEFERRED_TAX_ASSETS: "deferred_tax_assets",
    BS_OTHER_NONCURRENT_ASSETS: "other_noncurrent_assets",
    BS_TOTAL_NONCURRENT_ASSETS: "total_noncurrent_assets",
    BS_INVENTORIES: "inventories",
    BS_LONG_TERM_ASSETS_FOR_SALE: "long_term_assets_for_sale",
    BS_VAT: "vat",
    BS_RECEIVABLES: "receivables",
    BS_FINANCIAL_INVESTMENTS_CURRENT: "financial_investments_current",
    BS_CASH: "cash",
    BS_OTHER_CURRENT_ASSETS: "other_current_assets",
    BS_TOTAL_CURRENT_ASSETS: "total_current_assets",
    BS_TOTAL_ASSETS: "total_assets",
    BS_CHARTER_CAPITAL: "charter_capital",
    BS_ADDITIONAL_CAPITAL: "additional_capital",
    BS_RESERVE_CAPITAL: "reserve_capital",
    BS_RETAINED_EARNINGS: "retained_earnings",
    BS_TOTAL_EQUITY: "total_equity",
    BS_BORROWINGS_NONCURRENT: "borrowings_noncurrent",
    BS_DEFERRED_TAX_LIABILITIES: "deferred_tax_liabilities",
    BS_ESTIMATED_LIABILITIES_NONCURRENT: "estimated_liabilities_noncurrent",
    BS_DEFERRED_INCOME_NONCURRENT: "deferred_income_noncurrent",
    BS_OTHER_NONCURRENT_LIABILITIES: "other_noncurrent_liabilities",
    BS_TOTAL_NONCURRENT_LIABILITIES: "total_noncurrent_liabilities",
    BS_BORROWINGS_CURRENT: "borrowings_current",
    BS_ACCOUNTS_PAYABLE: "accounts_payable",
    BS_DEFERRED_INCOME_CURRENT: "deferred_income_current",
    BS_ESTIMATED_LIABILITIES_CURRENT: "estimated_liabilities_current",
    BS_OTHER_CURRENT_LIABILITIES: "other_current_liabilities",
    BS_TOTAL_CURRENT_LIABILITIES: "total_current_liabilities",
    BS_TOTAL_LIABILITIES: "total_liabilities",
}
