# ===== Отчёт о финансовых результатах (форма 0710002) =====

REVENUE = '2110'
OTHER_INCOMING = '2115'
COST_OF_SALES = '2120'
GROSS_PROFIT = '2100'
COMMERCIAL_EXPENSES = '2210'
MANAGEMENT_EXPENSES = '2220'
PROFIT_FROM_SALES = '2200'
INCOME_FROM_PARTICIPATION = '2310'
PERCENTAGE_RECEIVABLE = "2320"
PERCENTAGE_TO_PAY = "2330"
OTHER_PROFIT = '2340'
OTHER_EXPENSES = '2350'
PROFIT_FROM_CONTINUING_OPERATIONS = '2300'
ORGANIZATION_INCOME_TAX = '2410'
DEFERRED_ORGANIZATION_INCOME_TAX = '2412'
OTHER = '2460'
NET_PROFIT = '2400'
TOTAL_FINANCIAL_RESULT = '2500'

financial_results_consts = [
    REVENUE,
    OTHER_INCOMING,
    COST_OF_SALES,
    GROSS_PROFIT,
    COMMERCIAL_EXPENSES,
    MANAGEMENT_EXPENSES,
    PROFIT_FROM_SALES,
    INCOME_FROM_PARTICIPATION,
    PERCENTAGE_RECEIVABLE,
    PERCENTAGE_TO_PAY,
    OTHER_PROFIT,
    OTHER_EXPENSES,
    PROFIT_FROM_CONTINUING_OPERATIONS,
    ORGANIZATION_INCOME_TAX,
    DEFERRED_ORGANIZATION_INCOME_TAX,
    OTHER,
    NET_PROFIT,
    TOTAL_FINANCIAL_RESULT,
]

# Коды ОФР, которые по стандарту бухучёта всегда показываются в скобках (расходы).
# Используется как fallback, когда OCR не распознаёт скобки.
OFR_NEGATIVE_CODES = {
    COST_OF_SALES,           # 2120
    COMMERCIAL_EXPENSES,     # 2210
    MANAGEMENT_EXPENSES,     # 2220
    PERCENTAGE_TO_PAY,       # 2330
    OTHER_EXPENSES,          # 2350
    ORGANIZATION_INCOME_TAX, # 2410
    DEFERRED_ORGANIZATION_INCOME_TAX,  # 2412
}

# ===== Бухгалтерский баланс (форма 0710001) =====

# АКТИВ — I. Внеоборотные активы
BS_INTANGIBLE_ASSETS = '1110'
BS_FIXED_ASSETS = '1150'
BS_INVESTMENT_PROPERTY = '1160'
BS_FINANCIAL_INVESTMENTS_NONCURRENT = '1170'
BS_DEFERRED_TAX_ASSETS = '1180'
BS_OTHER_NONCURRENT_ASSETS = '1190'
BS_TOTAL_NONCURRENT_ASSETS = '1100'

# АКТИВ — II. Оборотные активы
BS_INVENTORIES = '1210'
BS_LONG_TERM_ASSETS_FOR_SALE = '1215'
BS_VAT = '1220'
BS_RECEIVABLES_LONG_TERM = '1230.1'
BS_RECEIVABLES_SHORT_TERM = '1230.2'
BS_FINANCIAL_INVESTMENTS_CURRENT = '1240'
BS_CASH = '1250'
BS_OTHER_CURRENT_ASSETS = '1260'
BS_TOTAL_CURRENT_ASSETS = '1200'
BS_TOTAL_ASSETS = '1600'

# ПАССИВ — III. Капитал
BS_CHARTER_CAPITAL = '1310'
BS_ADDITIONAL_CAPITAL = '1350'
BS_RESERVE_CAPITAL = '1360'
BS_RETAINED_EARNINGS = '1370'
BS_TOTAL_EQUITY = '1300'

# ПАССИВ — IV. Долгосрочные обязательства
BS_BORROWINGS_NONCURRENT = '1410'
BS_DEFERRED_TAX_LIABILITIES = '1420'
BS_ESTIMATED_LIABILITIES_NONCURRENT = '1430'
BS_DEFERRED_INCOME_NONCURRENT = '1440'
BS_OTHER_NONCURRENT_LIABILITIES = '1450'
BS_TOTAL_NONCURRENT_LIABILITIES = '1400'

# ПАССИВ — V. Краткосрочные обязательства
BS_BORROWINGS_CURRENT = '1510'
BS_ACCOUNTS_PAYABLE = '1520'
BS_DEFERRED_INCOME_CURRENT = '1530'
BS_ESTIMATED_LIABILITIES_CURRENT = '1540'
BS_OTHER_CURRENT_LIABILITIES = '1550'
BS_TOTAL_CURRENT_LIABILITIES = '1500'
BS_TOTAL_LIABILITIES = '1700'

balance_sheet_consts = [
    BS_INTANGIBLE_ASSETS, BS_FIXED_ASSETS, BS_INVESTMENT_PROPERTY,
    BS_FINANCIAL_INVESTMENTS_NONCURRENT, BS_DEFERRED_TAX_ASSETS,
    BS_OTHER_NONCURRENT_ASSETS, BS_TOTAL_NONCURRENT_ASSETS,
    BS_INVENTORIES, BS_LONG_TERM_ASSETS_FOR_SALE, BS_VAT,
    BS_RECEIVABLES_LONG_TERM, BS_RECEIVABLES_SHORT_TERM,
    BS_FINANCIAL_INVESTMENTS_CURRENT, BS_CASH,
    BS_OTHER_CURRENT_ASSETS, BS_TOTAL_CURRENT_ASSETS, BS_TOTAL_ASSETS,
    BS_CHARTER_CAPITAL, BS_ADDITIONAL_CAPITAL, BS_RESERVE_CAPITAL,
    BS_RETAINED_EARNINGS, BS_TOTAL_EQUITY,
    BS_BORROWINGS_NONCURRENT, BS_DEFERRED_TAX_LIABILITIES,
    BS_ESTIMATED_LIABILITIES_NONCURRENT, BS_DEFERRED_INCOME_NONCURRENT,
    BS_OTHER_NONCURRENT_LIABILITIES, BS_TOTAL_NONCURRENT_LIABILITIES,
    BS_BORROWINGS_CURRENT, BS_ACCOUNTS_PAYABLE, BS_DEFERRED_INCOME_CURRENT,
    BS_ESTIMATED_LIABILITIES_CURRENT, BS_OTHER_CURRENT_LIABILITIES,
    BS_TOTAL_CURRENT_LIABILITIES, BS_TOTAL_LIABILITIES,
]

# ===== Отчёт о движении денежных средств (форма 0710005) =====

# Денежные потоки от текущих операций
CF_RECEIPTS_OPERATING = '4110'
CF_RECEIPTS_SALES = '4111'
CF_RECEIPTS_RENT = '4112'
CF_RECEIPTS_INTEREST_RECEIVED = '4114'
CF_RECEIPTS_BUDGET = '4115'
CF_RECEIPTS_OTHER_OPERATING = '4119'
CF_PAYMENTS_OPERATING = '4120'
CF_PAYMENTS_SUPPLIERS = '4121'
CF_PAYMENTS_WAGES = '4122'
CF_PAYMENTS_INTEREST = '4123'
CF_PAYMENTS_INCOME_TAX = '4124'
CF_PAYMENTS_LEASE = '4125'
CF_PAYMENTS_OTHER_OPERATING = '4129'
CF_NET_OPERATING = '4100'

# Денежные потоки от инвестиционных операций
CF_RECEIPTS_INVESTING = '4210'
CF_RECEIPTS_NONCURRENT_SALES = '4211'
CF_RECEIPTS_EQUITY_SALES = '4212'
CF_RECEIPTS_DEBT_REPAYMENT = '4213'
CF_RECEIPTS_DIVIDENDS = '4214'
CF_RECEIPTS_OTHER_INVESTING = '4219'
CF_PAYMENTS_INVESTING = '4220'
CF_PAYMENTS_NONCURRENT_PURCHASE = '4221'
CF_PAYMENTS_EQUITY_PURCHASE = '4222'
CF_PAYMENTS_DEBT_PURCHASE = '4223'
CF_PAYMENTS_INTEREST_CAPITALIZED = '4224'
CF_PAYMENTS_OTHER_INVESTING = '4229'
CF_NET_INVESTING = '4200'

# Денежные потоки от финансовых операций
CF_RECEIPTS_FINANCING = '4310'
CF_RECEIPTS_LOANS = '4311'
CF_RECEIPTS_BONDS = '4314'
CF_RECEIPTS_OTHER_FINANCING = '4319'
CF_PAYMENTS_FINANCING = '4320'
CF_PAYMENTS_DIVIDENDS = '4322'
CF_PAYMENTS_DEBT_REPAYMENT = '4323'
CF_PAYMENTS_OTHER_FINANCING = '4329'
CF_NET_FINANCING = '4300'

# Итоги
CF_NET_CASH_FLOW = '4400'
CF_CASH_BEGINNING = '4450'
CF_CASH_END = '4500'
CF_FX_EFFECT = '4490'

cash_flow_consts = [
    CF_RECEIPTS_OPERATING, CF_RECEIPTS_SALES, CF_RECEIPTS_RENT,
    CF_RECEIPTS_INTEREST_RECEIVED, CF_RECEIPTS_BUDGET, CF_RECEIPTS_OTHER_OPERATING,
    CF_PAYMENTS_OPERATING, CF_PAYMENTS_SUPPLIERS, CF_PAYMENTS_WAGES,
    CF_PAYMENTS_INTEREST, CF_PAYMENTS_INCOME_TAX, CF_PAYMENTS_LEASE,
    CF_PAYMENTS_OTHER_OPERATING, CF_NET_OPERATING,
    CF_RECEIPTS_INVESTING, CF_RECEIPTS_NONCURRENT_SALES, CF_RECEIPTS_EQUITY_SALES,
    CF_RECEIPTS_DEBT_REPAYMENT, CF_RECEIPTS_DIVIDENDS, CF_RECEIPTS_OTHER_INVESTING,
    CF_PAYMENTS_INVESTING, CF_PAYMENTS_NONCURRENT_PURCHASE,
    CF_PAYMENTS_EQUITY_PURCHASE, CF_PAYMENTS_DEBT_PURCHASE,
    CF_PAYMENTS_INTEREST_CAPITALIZED, CF_PAYMENTS_OTHER_INVESTING, CF_NET_INVESTING,
    CF_RECEIPTS_FINANCING, CF_RECEIPTS_LOANS, CF_RECEIPTS_BONDS,
    CF_RECEIPTS_OTHER_FINANCING, CF_PAYMENTS_FINANCING, CF_PAYMENTS_DIVIDENDS,
    CF_PAYMENTS_DEBT_REPAYMENT, CF_PAYMENTS_OTHER_FINANCING, CF_NET_FINANCING,
    CF_NET_CASH_FLOW, CF_CASH_BEGINNING, CF_CASH_END, CF_FX_EFFECT,
]

# ===== Отчёт об изменениях капитала (форма 0710004) =====

EC_BALANCE_PREV_START = '3100'
EC_NET_PROFIT_PREV = '3211'
EC_DIVIDENDS_PREV = '3240'
EC_REVALUATION_EFFECT_PREV = '3241'
EC_TREASURY_SHARES_PREV = '3242'
EC_DIVIDENDS_SHAREHOLDERS_PREV = '3243'
EC_BALANCE_PREV_END = '3200'
EC_NET_PROFIT_CURR = '3311'
EC_DIVIDENDS_CURR = '3340'
EC_TREASURY_SHARES_CURR = '3341'
EC_BALANCE_CURR_END = '3100'  # повтор кода — итоговый баланс

equity_changes_consts = [
    '3100',                          # Остаток на начало предыдущего периода
    '3200',                          # Остаток на конец предыдущего периода
    '3300',                          # Остаток на конец текущего периода
    '3211', '3212', '3213',          # Чистая прибыль, прочий доход, совокупный доход (прошлый год)
    '3220', '3221', '3222', '3223',  # Увеличение капитала
    '3224', '3225', '3226',
    '3227',                          # Дивиденды (прошлый год)
    '3228', '3229',
    '3230',                          # Изменение добавочного капитала
    '3240', '3241', '3242', '3243',  # Прочие изменения
    '3311', '3312', '3313',          # Чистая прибыль, прочий доход, совокупный доход (текущий год)
    '3320', '3321', '3322', '3323',  # Увеличение капитала
    '3324', '3325', '3326',
    '3327',                          # Дивиденды (текущий год)
    '3328', '3329',
    '3330',
    '3340', '3341', '3342', '3343',  # Прочие изменения (текущий год)
]

# Коды строк отчёта об изменениях капитала, значения которых по стандарту
# бухучёта всегда отрицательные (уменьшают капитал).
# OCR часто убирает скобки вокруг отрицательных чисел — инвертируем знак явно.
#
# Коды чистой прибыли/убытка (3211, 3311) НЕ включены: они могут быть как
# положительными (прибыль), так и отрицательными (убыток), и их знак
# должен браться из OCR.
EC_NEGATIVE_CODES = {
    '3227', '3327',  # Дивиденды — всегда уменьшают капитал
    '3228', '3229',  # Уменьшение капитала (прошлый год)
    '3328', '3329',  # Уменьшение капитала (текущий год)
}